### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by lbourdages** [jebeaudet/ChRomeTC#3]
A Firefox-compatible version would be appreciated :)

**Comment by jebeaudet** [comment]
Add-on has been submitted Mozilla, it's awaiting review before being available. I'll update this issue when it'll be done. The name doesn't _really_ fit in a FF add-on, I should have thought this through ;)

It'll be available here : https://addons.mozilla.org/en-US/firefox/addon/chrometc/

**Comment by jebeaudet** [comment]
Just a heads up, as of today, I'm still in position 81 in the review queue (out of 401 now). It hasn't budged much lately though. At this rate, it should be approved in another month at least, I have to say their review process is not the best.

**Comment by jebeaudet** [comment]
Version 1.0.2 was refused due to the use of a font that was not local to the extension, I'm now back at the end of the queue with 1.0.3...

**Comment by jebeaudet** [comment]
It's live and approved! I changed the name also :D
https://addons.mozilla.org/en-US/firefox/addon/firetc/
